import '@styles/global.css'
import Spinner from "@components/spinner"
export const metadata  = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({children}) => {
  return (
      <html lang="en">
          <body >
          {/* <div className="main">
            <div className="gradient"/>
          </div> */}
            <header className="bg-sky-900 p-5 font-customFont">
            <h1 className="mt-10 mb-8 text-center capatalize text-8xl  italic font-bold text-stone-950">Styles Store</h1>
            </header>
          <hr  className="w-full "/>
          <main>{children}</main>
          
          </body>
          

      </html>
  )
}

export default RootLayout;